import type { Experience } from '../types';

export function makeExperience(overrides: Partial<Experience> = {}): Experience {
  return {
    slug: 'test-cruise',
    title: 'Test Cruise',
    tagline: 'A cruise for tests',
    category: 'music',
    hero: '',
    gallery: [],
    dates: 'Aug 14–17',
    month: 'Aug',
    nights: 3,
    route: { from: 'Mumbai', to: 'Goa', code: 'BOM ⚓ GOI' },
    ship: 'Cordelia Empress',
    priceFrom: 20000,
    rating: 4.8,
    reviewCount: 100,
    capacity: 1000,
    spotsLeft: 100,
    popularity: 50,
    featured: false,
    host: {
      name: 'Test Host',
      initials: 'TH',
      tagline: 'Hosting tests',
      eventsHosted: 5,
      rating: 4.9,
      verified: true,
    },
    description: ['A test experience.'],
    highlights: [],
    included: [],
    schedule: [],
    cabins: [
      {
        id: 'interior',
        name: 'Interior Cabin',
        blurb: 'Cosy and quiet.',
        sqft: 150,
        occupancy: 2,
        perks: [],
        price: 20000,
        left: 10,
        image: '',
      },
      {
        id: 'suite',
        name: 'Chairman Suite',
        blurb: 'The whole horizon.',
        sqft: 440,
        occupancy: 4,
        perks: [],
        price: 55000,
        left: 2,
        image: '',
      },
    ],
    addons: [
      { id: 'spa', name: 'Spa Pass', blurb: '', price: 3000, perPerson: true },
      { id: 'photos', name: 'Photo Package', blurb: '', price: 5000, perPerson: false },
    ],
    faqs: [],
    reviews: [],
    ...overrides,
  };
}
